language: node_js

os:
  - linux
#  - osx

matrix:
  allow_failures:
    - os: osx

node_js:
  - '6'
  - '7'

sudo: required
services:
  - docker

compiler: clang

env:
  global:
  - secure: "kCAwXdfcMv4l4ok5lO89ANbKXXwWQpn5/3qupSbhmX2NDIGUxyXze/cs90u9gF5hcT7ebq27ZJPEtu7pRov8MadfQM9BAd4ZZrHcMHWSkA0Iz+nM+m0Urwach6jkp2Iuwx15L2NHSis7f5PUKJcEv4Gnqs8jrCJzHHS7m7dO0Xo="
  - secure: "lBIk4BhdIkSmJtFUNp93UjDm445i9eF7nKA+oSiLRu+b9i/WeRLiKFI89tehexWeXBlyNhziBN16LrHmx3I86yZfEok9dBMA1JuzYBjrvpjRAflGcqaCFLV3axyyyNQRIh7Q+ziAlg0xg8HL752BpnfXO91g3jfDPjGxcvBb5xQ="


before_install:
  # Fix a problem with apt-get failing later, see http://docs.travis-ci.com/user/installing-dependencies/#Installing-Ubuntu-packages
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install --force-yes --yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
  # for code coverage
  - sudo apt-get install lcov
  # get commit message
  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  # put local node-pre-gyp on PATH
  - export PATH=./node_modules/.bin/:$PATH

install:
  # install dependencies first
  - npm install
  # build from source, run test and generate code coverage
  - NODE_OPENCV_DEBUG=true node lib/opencv.js
  - docker build -t peterbraden/node-opencv-ubuntu-14-04 -f test/Dockerfile-ubuntu-14-04 .

before_script:
  - node-gyp clean
  - sudo apt-get purge --yes libcv-dev
  - sudo apt-get purge --yes libopencv-dev
  - sudo apt-get purge --yes libhighgui-dev

script:
  - npm test

after_success:
  # if success then query and display all published binaries
  - node-pre-gyp info
  # Upload coverage to codecov
  - bash <(curl -s https://codecov.io/bash) -s coverage -f *.info
